name: Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag x4m3/api.epi.today:latest

    - name: Push the latest Docker image
      run: docker push x4m3/api.epi.today:latest